<a href="https://colab.research.google.com/github/yosephabate/winc_datascience/blob/main/numpy_favtutor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import numpy library
import numpy as np

In [ ]:
# print current np version
np.__version__

'1.19.5'

In [ ]:
# adding two equal shaped ndarray(s)
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[10,11,12],
              [13,14,15]])

In [ ]:
a.shape

(2, 3)

In [ ]:
b.shape

(2, 3)

In [ ]:
c = a + b
c

array([[11, 13, 15],
       [17, 19, 21]])

In [ ]:
# multiply an ndarray by a scalar value
b = 2 * a
b

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
# create a 4x4 dimension identity matrix
i = np.eye(4)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# create a list with values ranging from 0 to 26
a = np.array([x for x in range(27)])
a.shape

(27,)

In [ ]:
# reshaping an existing ndarray
o = a.reshape((3,3,3))

In [ ]:
o

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
# array datatype conversion
a = np.array([[2.5, 3.8, 0],
              [4.7, 2.9, 1.56]])
a

array([[2.5 , 3.8 , 0.  ],
       [4.7 , 2.9 , 1.56]])

In [ ]:
a.dtype

dtype('float64')

In [ ]:
# convert float to int
o = a.astype('int')
o

array([[2, 3, 0],
       [4, 2, 1]])

In [ ]:
o.dtype

dtype('int64')

In [ ]:
# convert int to boolean
o = o.astype('bool')
o

array([[ True,  True, False],
       [ True,  True,  True]])

In [ ]:
i = np.eye(4)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
o = i.astype('bool')
o

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [ ]:
# stacking ndarrays
a1 = np.array([[1,2,3],
               [4,5,6]])

a2 = np.array([[7,8,9],
               [10,11,12]])

In [ ]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
o = np.hstack((a1, a2))
o

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
o = np.vstack((a1, a2))
o

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8],[9,10]])
np.vstack((a1, a2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
# custom sequence generation
list_of_numbers = [x for x in range(0, 101, 2)]
o = np.array(list_of_numbers)
o

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [ ]:
# matching positions
a = np.array([1,2,3,4,5])
b = np.array([1,3,2,4,5])
np.where(a == b)

(array([0, 3, 4]),)

In [ ]:
for i in np.where(a == b):
  print(a[i])

[1 4 5]


In [ ]:
# generation of equally spaced number within a range
o = np.linspace(0, 100, 5)
o

array([  0.,  25.,  50.,  75., 100.])

In [ ]:
o = np.linspace(0, 1, 5)
o

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# matrix generation with one particular value
o = np.ones((2, 3))
o
o = o * 5
o = o.astype('int')
o

array([[5, 5, 5],
       [5, 5, 5]])

In [ ]:
o = np.full((2, 3), 5)
o

array([[5, 5, 5],
       [5, 5, 5]])

In [ ]:
o = np.full((3, 3), 'True')
o

array([['True', 'True', 'True'],
       ['True', 'True', 'True'],
       ['True', 'True', 'True']], dtype='<U4')

In [ ]:
o = np.full((3, 3), 1)
o

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
o = np.ones((3,3)).astype('int')
o

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
# array generation by repeatition
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
o = np.tile(a, 10)
o

array([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1,
        2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4,
        5, 6, 4, 5, 6, 4, 5, 6]])

In [ ]:
o.shape

(2, 30)

In [ ]:
# array generation or random integers within a range
np.random.seed(123)
o = np.random.randint(0, 10, size=(5, 5))
o

array([[2, 2, 6, 1, 3],
       [9, 6, 1, 0, 1],
       [9, 0, 0, 9, 3],
       [4, 0, 0, 4, 1],
       [7, 3, 2, 4, 7]])

In [ ]:
np.random.seed(12)
o = np.random.randint(0, 10, size=(5, 5))
o

array([[6, 1, 2, 3, 3],
       [0, 6, 1, 4, 5],
       [9, 2, 6, 0, 5],
       [8, 2, 9, 3, 4],
       [3, 1, 7, 0, 2]])

In [ ]:
# array gernation of random number following normal distribution
np.random.seed(123)
o = np.random.normal(size=(3,3))
o

array([[-1.0856306 ,  0.99734545,  0.2829785 ],
       [-1.50629471, -0.57860025,  1.65143654],
       [-2.42667924, -0.42891263,  1.26593626]])

In [ ]:
# matrix multiplication
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.array([[2,3,4],
              [5,6,7],
              [8,9,10]])
a * b # wrong marix multiplication

array([[ 2,  6, 12],
       [20, 30, 42],
       [56, 72, 90]])

In [ ]:
a@b # correct matrix multiplication

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

In [ ]:
np.matmul(a, b) # correct matrix multiplication

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

In [ ]:
b@a

array([[ 42,  51,  60],
       [ 78,  96, 114],
       [114, 141, 168]])

In [ ]:
# matrix transpose
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
a_transpose = a.T
a_transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
a@a_transpose

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [ ]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
b = np.linalg.inv(a)

In [ ]:
a@b

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [ ]:
# sine of an angle (radians)
angles = np.array([3.14, 3.14/2, 6.28, 3*3.14/2])
sine_of_angles = np.sin(angles)
sine_of_angles

array([ 0.00159265,  0.99999968, -0.0031853 , -0.99999715])

In [ ]:
# cosine of an angle (radians)
angles = np.array([3.14, 3.14/2, 6.28, 3*3.14/2])
sine_of_angles = np.cos(angles)
sine_of_angles

array([-9.99998732e-01,  7.96326711e-04,  9.99994927e-01, -2.38897811e-03])

In [ ]:
# order array elements
array = np.array([10,1,5,2])
indexes = np.argsort(array)
indexes

array([1, 3, 2, 0])

In [ ]:
for i in indexes:
  print(array[i])

1
2
5
10
